config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users

  root to: "pages#home"
  get '/my_library', to: 'pages#my_library'
  get '/search', to: 'search#index'

  resources :books do
    resources :sessions, only: [:show, :index] do
      resources :attendees, only: [:create]
      resources :agendas do
        member do
          post 'upvote'
          post 'downvote'
        end
      end
      post 'join', on: :member
      post 'rsvp', on: :member
      delete 'rsvp', to: 'sessions#revoke_rsvp'
    end
    resources :reviews, only: [:new, :create]
  end

  # Add :create here to handle session creation
  resources :sessions, only: [:show, :index, :create] do
    resources :attendees, only: [:create]
    post 'join', on: :member
  end

  resources :reviews, only: [:edit, :update, :show, :destroy]

  post '/add_book_to_bookshelf', to: 'bookshelves#add_book_to_bookshelf'
  post '/remove_book_from_bookshelf', to: 'bookshelves#remove_book_from_bookshelf'
  post '/create_meeting', to: 'meetings#create_meeting'
  post '/initiate_call', to: 'messages#initiate_call'



  resources :topics
  resources :bookshelf_books
  resources :bookshelves
  resources :chatrooms, only: :show

  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :session
  belongs_to :user
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: %i[ show edit update destroy ]

  # GET /topics or /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1 or /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics or /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to topic_url(@topic), notice: "Topic was successfully created." }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1 or /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to topic_url(@topic), notice: "Topic was successfully updated." }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1 or /topics/1.json
  def destroy
    @topic.destroy!

    respond_to do |format|
      format.html { redirect_to topics_url, notice: "Topic was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def topic_params
      params.require(:topic).permit(:session_id, :description, :user_id, :votes)
    end
end

app/views/topics/_form.html.erb
<%= simple_form_for(@topic) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :session %>
    <%= f.input :description %>
    <%= f.association :user %>
    <%= f.input :votes %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/topics/_topic.html.erb
<div id="<%= dom_id topic %>">
  <p>
    <strong>Session:</strong>
    <%= topic.session_id %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= topic.description %>
  </p>

  <p>
    <strong>User:</strong>
    <%= topic.user_id %>
  </p>

  <p>
    <strong>Votes:</strong>
    <%= topic.votes %>
  </p>

</div>

app/views/topics/edit.html.erb
<h1>Editing topic</h1>

<%= render "form", topic: @topic %>

<br>

<div>
  <%= link_to "Show this topic", @topic %> |
  <%= link_to "Back to topics", topics_path %>
</div>

app/views/topics/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Topics</h1>

<div id="topics">
  <% @topics.each do |topic| %>
    <%= render topic %>
    <p>
      <%= link_to "Show this topic", topic %>
    </p>
  <% end %>
</div>

<%= link_to "New topic", new_topic_path %>

app/views/topics/new.html.erb
<h1>New topic</h1>

<%= render "form", topic: @topic %>

<br>

<div>
  <%= link_to "Back to topics", topics_path %>
</div>

app/views/topics/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @topic %>

<div>
  <%= link_to "Edit this topic", edit_topic_path(@topic) %> |
  <%= link_to "Back to topics", topics_path %>

  <%= button_to "Destroy this topic", @topic, method: :delete %>
</div>