config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users

  root to: "pages#home"
  get '/my_library', to: 'pages#my_library'
  get '/search', to: 'search#index'

  resources :books do
    resources :sessions, only: [:show, :index] do
      resources :attendees, only: [:create]
      resources :agendas do
        member do
          post 'upvote'
          post 'downvote'
        end
      end
      post 'join', on: :member
      post 'rsvp', on: :member
      delete 'rsvp', to: 'sessions#revoke_rsvp'
    end
    resources :reviews, only: [:new, :create]
  end

  # Add :create here to handle session creation
  resources :sessions, only: [:show, :index, :create] do
    resources :attendees, only: [:create]
    post 'join', on: :member
  end

  resources :reviews, only: [:edit, :update, :show, :destroy]

  post '/add_book_to_bookshelf', to: 'bookshelves#add_book_to_bookshelf'
  post '/remove_book_from_bookshelf', to: 'bookshelves#remove_book_from_bookshelf'
  post '/create_meeting', to: 'meetings#create_meeting'
  post '/initiate_call', to: 'messages#initiate_call'



  resources :topics
  resources :bookshelf_books
  resources :bookshelves
  resources :chatrooms, only: :show

  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end

  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/shared/_counter.html.erb
<span class="counter-pill"><%= @sessions_count_today %> Today</span>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container-footer">
    <div class="row">
      <div class="col-md-6">
        <%= image_tag "badbook-logo.png", class: "footer-logo" %>
        <p class="logo-text">Your virtual bookclub for good (and bad) books</p>
      </div>
      <div class="col-md-6">
        <div class="row">
          <div class="col-md-4">
            <p class="footer-links-header">BROWSE</p>
            <ul class="list-unstyled footer-links">
              <li><%= link_to "Books", books_path %></li>
              <li><%= link_to "Bookclubs", sessions_path %></li>
            </ul>
          </div>
        <% unless user_signed_in? %>
          <div class="col-md-4">
            <p class="footer-links-header">JOIN</p>
            <ul class="list-unstyled footer-links">
              <li><%= link_to "Sign Up", new_user_registration_path %></li>
            </ul>
          </div>
        <% end %>
          <div class="col-md-4">
            <p class="footer-links-header">FOLLOW</p>
            <ul class="list-unstyled footer-social">
              <li><a href="https://github.com/DDF93/badbook"><i class="fab fa-github"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12 text-center">
        <p class="copyright">&copy; <%= Time.now.year %> Badbook  •  Privacy  •  Terms</p>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-badbook sticky-top solid-navbar" id="navbar">
  <div class="container-fluid">
    <div class="d-flex align-items-center">

      <%= link_to root_path, class: "navbar-brand mr-auto" do %>
        <%= image_tag "badbook-logo.png" %>
      <% end %>

      <div class="d-flex align-items-center ml-3">
        <%= form_with url: "/search", method: :get, class: "form-inline d-flex" do %>
          <div class="input-group">
            <%= text_field_tag :query,
                  params[:query],
                  class: "form-control search-input",
                  placeholder: "Find books..."
            %>
            <button type="submit" class="btn btn-outline-success search-button">
              <i class="fa-solid fa-magnifying-glass"></i>
            </button>
          </div>
        <% end %>
      </div>
    </div>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Books", books_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <div class="link-with-counter">
              <%= link_to "Bookclubs", sessions_path, class: "nav-link" %>
              <%= render 'shared/counter' %>
            </div>
          </li>
          <li class="nav-item">
            <%= link_to "My Library", my_library_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= image_tag "katniss.jpg", class: "avatar", alt: "dropdown menu" %>
            </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Logout", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item active">
            <%= link_to "Books", books_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Bookclubs", sessions_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>