config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users

  root to: "pages#home"
  get '/my_library', to: 'pages#my_library'
  get '/search', to: 'search#index'

  resources :books do
    resources :sessions, only: [:show, :index] do
      resources :attendees, only: [:create]
      resources :agendas do
        member do
          post 'upvote'
          post 'downvote'
        end
      end
      post 'join', on: :member
      post 'rsvp', on: :member
      delete 'rsvp', to: 'sessions#revoke_rsvp'
    end
    resources :reviews, only: [:new, :create]
  end

  # Add :create here to handle session creation
  resources :sessions, only: [:show, :index, :create] do
    resources :attendees, only: [:create]
    post 'join', on: :member
  end

  resources :reviews, only: [:edit, :update, :show, :destroy]

  post '/add_book_to_bookshelf', to: 'bookshelves#add_book_to_bookshelf'
  post '/remove_book_from_bookshelf', to: 'bookshelves#remove_book_from_bookshelf'
  post '/create_meeting', to: 'meetings#create_meeting'
  post '/initiate_call', to: 'messages#initiate_call'



  resources :topics
  resources :bookshelf_books
  resources :bookshelves
  resources :chatrooms, only: :show

  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/attendee.rb
class Attendee < ApplicationRecord
  belongs_to :user
  belongs_to :session
  validates :user_id, uniqueness: { scope: :session_id, message: "You are already attending this session." }
end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController
  before_action :set_attendee, only: %i[ show edit update destroy ]
  before_action :find_session

  def index
    @attendees = Attendee.all
  end

  def show
  end

  def new
    @attendee = Attendee.new
  end

  def edit
  end

  def create
    if @session.attendees.count < @session.capacity
      attendee = @session.attendees.build(user: current_user)

      if attendee.save
        redirect_to @session, notice: "You're now attending the session."
      else
        redirect_to @session, alert: "Could not attend the session."
      end
    else
      redirect_to @session, alert: "Session is at full capacity."
    end
  end

  def destroy
    @session = Session.find(params[:session_id])
    @attendee = @session.attendees.find_by(user_id: current_user.id)
    if @attendee.destroy
      render json: { message: "RSVP revoked successfully" }, status: :ok
    else
      render json: { error: "Failed to revoke RSVP" }, status: :unprocessable_entity
    end
  end

private

def attendee_params
  params.require(:attendee).permit(:user_id, :session_id)
end


  # PATCH/PUT /attendees/1 or /attendees/1.json
  def update
    respond_to do |format|
      if @attendee.update(attendee_params)
        format.html { redirect_to attendee_url(@attendee), notice: "Attendee was successfully updated." }
        format.json { render :show, status: :ok, location: @attendee }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @attendee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attendees/1 or /attendees/1.json
  def destroy
    @attendee.destroy!

    respond_to do |format|
      format.html { redirect_to attendees_url, notice: "Attendee was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_attendee
      @attendee = Attendee.find(params[:id])
    end

    def attendee_params
      params.require(:attendee).permit(:user_id, :session_id)
    end

    def find_session
      @session = Session.find(params[:session_id])
    end
end

app/views/attendees/_attendee.html.erb
<div id="<%= dom_id attendee %>">
  <p>
    <strong>User:</strong>
    <%= attendee.user_id %>
  </p>

  <p>
    <strong>Session:</strong>
    <%= attendee.session_id %>
  </p>

</div>

app/views/attendees/_form.html.erb
<%= simple_form_for(@attendee) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :user %>
    <%= f.association :session %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/attendees/edit.html.erb
<h1>Editing attendee</h1>

<%= render "form", attendee: @attendee %>

<br>

<div>
  <%= link_to "Show this attendee", @attendee %> |
  <%= link_to "Back to attendees", attendees_path %>
</div>

app/views/attendees/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Attendees</h1>

<div id="attendees">
  <% @attendees.each do |attendee| %>
    <%= render attendee %>
    <p>
      <%= link_to "Show this attendee", attendee %>
    </p>
  <% end %>
</div>

<%= link_to "New attendee", new_attendee_path %>

app/views/attendees/new.html.erb
<h1>New attendee</h1>

<%= render "form", attendee: @attendee %>

<br>

<div>
  <%= link_to "Back to attendees", attendees_path %>
</div>

app/views/attendees/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @attendee %>

<div>
  <%= link_to "Edit this attendee", edit_attendee_path(@attendee) %> |
  <%= link_to "Back to attendees", attendees_path %>

  <%= button_to "Destroy this attendee", @attendee, method: :delete %>
</div>