config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users

  root to: "pages#home"
  get '/my_library', to: 'pages#my_library'
  get '/search', to: 'search#index'

  resources :books do
    resources :sessions, only: [:show, :index] do
      resources :attendees, only: [:create]
      resources :agendas do
        member do
          post 'upvote'
          post 'downvote'
        end
      end
      post 'join', on: :member
      post 'rsvp', on: :member
      delete 'rsvp', to: 'sessions#revoke_rsvp'
    end
    resources :reviews, only: [:new, :create]
  end

  # Add :create here to handle session creation
  resources :sessions, only: [:show, :index, :create] do
    resources :attendees, only: [:create]
    post 'join', on: :member
  end

  resources :reviews, only: [:edit, :update, :show, :destroy]

  post '/add_book_to_bookshelf', to: 'bookshelves#add_book_to_bookshelf'
  post '/remove_book_from_bookshelf', to: 'bookshelves#remove_book_from_bookshelf'
  post '/create_meeting', to: 'meetings#create_meeting'
  post '/initiate_call', to: 'messages#initiate_call'



  resources :topics
  resources :bookshelf_books
  resources :bookshelves
  resources :chatrooms, only: :show

  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :author, presence: true
  validates :date, presence: true
  validates :description, presence: true
  has_many :bookshelf_books
  has_many :bookshelves, through: :bookshelf_books
  has_many :reviews, dependent: :destroy
  has_many :sessions

  include PgSearch::Model

  pg_search_scope :search_book,
    against: [:title, :description, :author, :genre],
    using: {
      tsearch: { prefix: true }
    }

  def average_rating
    reviews.average(:rating).to_f.round(1)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:mark_as_read]
  before_action :set_session, only: [:show]

  def index
    @bookshelves = Bookshelf.where(user_id: 1)
    read_books_shelf = current_user.bookshelves.find_by(name: 'Read Books')
    @read_books = read_books_shelf.present? ? read_books_shelf.books.to_a : []
  end

  def show
    @book = Book.find(params[:id])
    @upcoming_sessions = @book.sessions.includes(:attendees).where('start_time > ?', Time.current).order(start_time: :asc)



    clean_description = @book.description
                     .gsub(/\A"|"\Z/, '')
                     .gsub(/--Publisher's description\.\Z/, '')
                     .gsub(/<\/?b>|<\/?i>|<\/?p>|<br>/, '')
                     .strip

    sentence_case_description = clean_description.downcase.capitalize
    preview_characters = sentence_case_description[0...350]
    description_longer_than_250_characters = sentence_case_description.length > 350

    @preview_description = preview_characters
    @full_description = sentence_case_description
    @description_longer_than_250 = description_longer_than_250_characters

    # Initialize @review
    @review = Review.new
    @bookshelves = Bookshelf.where(user_id: 1)
    read_books_shelf = current_user.bookshelves.find_by(name: 'Read Books')
    @read_books = read_books_shelf.present? ? read_books_shelf.books.to_a : []
  end

  def mark_as_read
    @read_books << @book
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully marked as read.' }
      format.json { head :no_content }
    end

  end

private

  def set_book
    @book = Book.find(params[:book_id])
  end

  def set_session
    @book = Book.find(params[:id])
    @sessions = @book.sessions
  end

  # def get_books_by_genre(genre)
  #   book_ids = []
  #   url = "https://www.googleapis.com/books/v1/volumes?q=subject:#{genre}&maxResults=20"

  #   begin
  #     data = URI.open(url).read
  #   rescue OpenURI::HTTPError => e
  #     if e.message.include?('429')
  #       sleep(5)  # Back off for 5 seconds before retrying
  #       retry
  #     else
  #       # Handle other HTTP errors
  #       puts "HTTP Error: #{e.message}"
  #       return []  # Return an empty array if there's an error
  #     end
  #   end

  #   book_json = JSON.parse(data)
  #   return [] unless book_json["items"]

  #   books = []
  #   book_json["items"].each do |book|
  #     book_ids << book["id"]
  #   end

  #   book_ids.each do |book_id|
  #     begin
  #       id_data = URI.open("https://www.googleapis.com/books/v1/volumes/#{book_id}").read
  #     rescue OpenURI::HTTPError => e
  #       if e.message.include?('429')
  #         sleep(5)  # Back off for 5 seconds before retrying
  #         retry
  #       else
  #         # Handle other HTTP errors
  #         puts "HTTP Error: #{e.message}"
  #         next  # Continue to the next book ID if there's an error
  #       end
  #     end

  #     id_json = JSON.parse(id_data)
  #     title = id_json.dig("volumeInfo", "title")
  #     authors = id_json.dig("volumeInfo", "authors")&.join(", ")
  #     published_date = id_json.dig("volumeInfo", "publishedDate")
  #     description = id_json.dig("volumeInfo", "description")
  #     image_url = id_json.dig("volumeInfo", "imageLinks", "thumbnail")

  #     book_add = {
  #       google_id: book_id,
  #       title: title,
  #       author: authors,
  #       date: published_date,
  #       description: description,
  #       image_url: image_url
  #     }
  #     books << book_add
  #   end
  # end
end

app/views/books/_book.html.erb
<div id="<%= dom_id book %>">
  <p>
    <strong>Title:</strong>
    <%= book.title %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= book.author %>
  </p>

  <p>
    <strong>Genre:</strong>
    <%= book.genre %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= book.description %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= book.date %>
  </p>

</div>

app/views/books/_book_show_buttons.html.erb
<div class="position-relative d-flex justify-content-between">
  <% if user_signed_in? %>
      <% book_read = @read_books.include?(book) %>
      <% needed_shelf = Bookshelf.where(user: current_user, name: "Read Books") %>
      <% if book_read  %>
      <button class="show-read-status-btn <%= 'read' if book_read %>" data-controller="show-mark" data-mark-target="show-mark"  data-bookshelf-id="<%= needed_shelf.first.id %>" data-book-id="<%= book[:id] %>" data-toggle="tooltip" data-action="click->show-mark#remove" title="<%= book_read ? 'Mark as unread' : 'Mark as read' %>">
        <i class="fa <%= book_read ? 'fa-check' : 'fa-check' %>"></i>
      </button>
      <% else  %>
      <button class="show-read-status-btn <%= 'read' if book_read %>" data-controller="show-mark" data-mark-target="show-mark"  data-bookshelf-id="<%= needed_shelf.first.id %>" data-book-id="<%= book[:id] %>" data-toggle="tooltip" data-action="click->show-mark#toggleRead" title="<%= book_read ? 'Mark as unread' : 'Mark as read' %>">
        <i class="fa <%= book_read ? 'fa-check' : 'fa-check' %>"></i>
      </button>
          <% end  %>

      <div data-controller="dropdown">
      <button class="show-add-btn" data-action="click->dropdown#toggle" data-toggle="tooltip" title="Add to Bookshelf">
        <i class="fa fa-plus"></i>
      </button>

    <div class="dropdown d-flex flex-column flex-md-row mt-1 align-items-center justify-content-center d-none" data-dropdown-target="menu">
      <ul class="dropdown-menu d-grid gap-2 p-3 shadow w-240px position-relative" data-bs-theme="light" style="max-height: none; max-width: none;" overflow-y: auto;">
        <% Bookshelf.where(user_id: current_user).each do |shelf| %>
          <% if shelf.name == "Read Books" %>
          <% elsif BookshelfBook.where(book_id: book.id, bookshelf_id: shelf.id).exists? %>
            <li>
              <a class="dropdown-item" href="#" data-bookshelf-id="<%= shelf.id %>" data-book-id="<%= book.id %>" data-action="click->dropdown#removeFromBookshelf">
                <%= shelf.name %> <i class="fa-solid fa-circle-check" style="margin-left: 4px;"></i>
              </a>
            </li>
          <% else %>
            <li>
              <a class="dropdown-item" href="#" data-bookshelf-id="<%= shelf.id %>" data-book-id="<%= book.id %>" data-action="click->dropdown#addToBookshelf">
                <%= shelf.name %> <i class="fa-regular fa-circle" style="margin-left: 4px;"></i>
              </a>
            </li>
            <li><hr class="dropdown-divider"></li>
          <% end %>
        <% end %>
        <li>
          <a class="dropdown-item rounded-2" href="#" data-action="click->modal#open" data-target="modal.trigger" data-bs-toggle="modal" data-bs-target="#createBookshelfModal" data-controller="modal">
            <i class="fa-solid fa-plus" style="margin-right: 4px;"></i> New Bookshelf
          </a>
        </li>
      </ul>
    </div>

    <div class="modal fade" id="createBookshelfModal" tabindex="-1" aria-labelledby="createBookshelfModalLabel" aria-hidden="true" data-controller="modal">
        <div class="modal-dialog">
          <div class="modal-content modal-white-background">
            <div class="modal-header">
              <p class="modal-title" id="createBookshelfModalLabel">New Bookshelf</p>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <form id="createBookshelfForm" data-action="submit->modal#submit" method="post" action="/bookshelves">
                <div class="mb-3">
                  <label for="bookshelfName" class="form-label">Bookshelf Name</label>
                  <input type="text" class="form-control" id="bookshelfName" name="bookshelf[name]">
                </div>
                <button type="submit" class="bold-button">Create</button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>

  <% end %>
</div>

app/views/books/_book_tile.html.erb
<div  class="book-tile" style="position: relative; width: 200px;" data-controller="dropdown">
  <% if book[:image_url].present? %>
    <%= link_to image_tag(book[:image_url], class: "img-fluid book-cover", alt: book[:title]), book_path(book[:id]) %>
  <% else %>
    <p>No image available</p>
  <% end %>

  <% if user_signed_in? %>
    <% book_read = @read_books.include?(book) %>
    <% needed_shelf = Bookshelf.where(user: current_user, name: "Read Books") %>
    <% if book_read  %>
    <button class="read-status-btn <%= 'read' if book_read %>" data-controller="mark" data-mark-target="mark"  data-bookshelf-id="<%= needed_shelf.first.id %>" data-book-id="<%= book[:id] %>" data-toggle="tooltip" data-action="click->mark#remove" title="<%= book_read ? 'Mark as unread' : 'Mark as read' %>">
      <i class="fa <%= book_read ? 'fa-check' : 'fa-check' %>"></i>
    </button>
    <% else  %>
    <button class="read-status-btn <%= 'read' if book_read %>" data-controller="mark" data-mark-target="mark"  data-bookshelf-id="<%= needed_shelf.first.id %>" data-book-id="<%= book[:id] %>" data-toggle="tooltip" data-action="click->mark#toggleRead" title="<%= book_read ? 'Mark as unread' : 'Mark as read' %>">
      <i class="fa <%= book_read ? 'fa-check' : 'fa-check' %>"></i>
    </button>
        <% end  %>

  <button class="add-btn" data-action="click->dropdown#toggle" data-toggle="tooltip" title="Add to Bookshelf">
    <i class="fa fa-plus"></i>
  </button>

  <div class="dropdown d-flex flex-column flex-md-row mt-1 align-items-center justify-content-center d-none" data-dropdown-target="menu">
    <ul class="dropdown-menu d-grid gap-2 p-2 shadow w-240px position-relative" data-bs-theme="light" style="max-height: none; max-width: none;" overflow-y: auto;">
      <% Bookshelf.where(user_id: current_user).each do |shelf| %>
        <% if shelf.name == "Read Books" %>
        <% elsif BookshelfBook.where(book_id: book.id, bookshelf_id: shelf.id).exists? %>
          <li>
            <a class="dropdown-item" href="#" data-bookshelf-id="<%= shelf.id %>" data-book-id="<%= book.id %>" data-action="click->dropdown#removeFromBookshelf">
              <%= shelf.name %> <i class="fa-regular fa-circle-check" style="margin-left: 4px;"></i>
            </a>
          </li>
          <li><hr class="dropdown-divider"></li>
        <% else %>
          <li>
            <a class="dropdown-item" href="#" data-bookshelf-id="<%= shelf.id %>" data-book-id="<%= book.id %>" data-action="click->dropdown#addToBookshelf">
              <%= shelf.name %> <i class="fa-regular fa-circle" style="margin-left: 4px;"></i>
            </a>
          </li>
          <li><hr class="dropdown-divider"></li>
        <% end %>
      <% end %>
      <li>
        <a class="dropdown-item rounded-2" href="#" data-action="click->modal#open" data-target="modal.trigger" data-bs-toggle="modal" data-bs-target="#createBookshelfModal" data-controller="modal">
          <i class="fa-solid fa-plus" style="margin-right: 4px;"></i> New Bookshelf
        </a>
      </li>
    </ul>
  </div>

  <div class="modal fade" id="createBookshelfModal" tabindex="-1" aria-labelledby="createBookshelfModalLabel" aria-hidden="true" data-controller="modal">
    <div class="modal-dialog">
      <div class="modal-content modal-white-background">
        <div class="modal-header">
          <p class="modal-title" id="createBookshelfModalLabel">New Bookshelf</p>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form id="createBookshelfForm" data-action="submit->modal#submit" method="post" action="/bookshelves">
            <div class="mb-3">
              <label for="bookshelfName" class="form-label">Bookshelf Name</label>
              <input type="text" class="form-control" id="bookshelfName" name="bookshelf[name]">
            </div>
            <button type="submit" class="bold-button">Create</button>
          </form>
        </div>
      </div>
    </div>
  </div>
  <% end %>
    <div class="book-info" data-dropdown-target="info">
      <%= link_to book_path(book) do %>
        <div class="book-title"><%= book[:title] %></div>
      <% end %>

      <div class="book-author"><%= book[:author] %></div>
    </div>
</div>

app/views/books/_carousel.html.erb
<div class="carousel-inner">
  <% books.each_slice(5).with_index do |books_slice, index| %>
    <div class="carousel-item <%= 'active' if index.zero? %>">
      <div class="row justify-content-center">
        <% books_slice.each do |book| %>
          <div class="col-md-2 each-book">
            <%= render 'books/book_tile', book: book %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/books/_find_books.html.erb
<% require 'json'
require 'open-uri'

initial_books = ["I12oPwAACAAJ", "u7XrDwAAQBAJ", "xDtkEAAAQBAJ", "49nUEAAAQBAJ", "hIx4EAAAQBAJ", "tkZFEAAAQBAJ", "Es_PCwAAQBAJ",
                 "hxL2qWMAgv8C", "jVB1DwAAQBAJ", "nNjTDwAAQBAJ", "wxBbEAAAQBAJ", "cpAREAAAQBAJ", "OyCtDwAAQBAJ", "iBg_EAAAQBAJ", "lGjFtMRqp_YC"]

initial_books.each do |book_id|
  begin
    data = URI.open("https://www.googleapis.com/books/v1/volumes/#{book_id}").read
    book_json = JSON.parse(data)

    title = book_json.dig("volumeInfo", "title")
    authors = book_json.dig("volumeInfo", "authors")&.join(", ")
    published_date = book_json.dig("volumeInfo", "publishedDate")
    description = book_json.dig("volumeInfo", "description")

  rescue StandardError => e
    puts "Error occurred while processing book with ID #{book_id}: #{e.message}"
  end
 %>

 <h1><%= title %></h1>

 <% end %>

app/views/books/_form.html.erb
<%= simple_form_for(@book) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :author %>
    <%= f.input :genre %>
    <%= f.input :description %>
    <%= f.input :date %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/books/_join_session.html.erb
<%= button_to book_session_rsvp_path(book, session),
    method: :post,
    data: { turbo_frame: "_self" },
    class: "btn-join-show" do %>
  <i class='fa-solid fa-circle fa-xs' style='margin-right: 3px;'></i> Join
<% end %>

app/views/books/_revoke_rsvp.html.erb
<button class="btn-rsvp-revoke" data-rsvp-target='button' data-action="click->rsvp#handleClick" data-book-id="<%= book.id %>" data-session-id="<%= session.id %>">Cancel</button>

app/views/books/_rsvp.html.erb
<button class="btn-rsvp"  data-rsvp-target="button" data-action="click->rsvp#handleClick" data-book-id="<%= book.id %>" data-session-id="<%= session.id %>">Attend</button>

app/views/books/_sessions_panel.html.erb
<div class="sessions-panel">
  <div class="d-flex justify-content-between align-items-center mb-2">
    <p class="sessions-panel-header mb-0">Upcoming Bookclubs</p>
    <% if current_user.host? %>
      <button class="btn-new-session" data-bs-toggle="modal" data-bs-target="#newSessionModal">
        <i class="fa fa-plus pe-1"></i>
        New
      </button>
    <% end %>
  </div>

  <div class="modal fade" id="newSessionModal" tabindex="-1" aria-labelledby="newSessionModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content modal-white-background">
        <div class="modal-header">
          <h5 class="modal-title" id="newSessionModalLabel">Create a new session</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <%= form_with(model: Session.new, url: sessions_path, method: :post) do |form| %>
            <div class="mb-3">
              <%= form.label :start_time, 'Date and Time' %>
              <%= form.datetime_local_field :start_time, required: true, class: 'form-control' %>
              <%= form.hidden_field :book_id, value: @book.id %>
            </div>
            <div class="mb-3">
              <%= form.label :capacity, 'Number of attendees' %>
              <%= form.number_field :capacity, required: true, class: 'form-control' %>
            </div>
            <div class="modal-footer">
              <%= form.submit 'Create Session', class: 'bold-button' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <table id="books-sessions-table">
  <tbody>
    <% if @upcoming_sessions.any? %>
    <% @upcoming_sessions.each do |session| %>
      <tr data-controller = "rsvp">
        <td class="book-session-start-time">
          <span class="session-date"><%= session.start_time.strftime("%a %d %b") %></span>
          <br>
          <span class="session-time"><%= session.start_time.strftime("%l:%M%p") %></span>
        </td>
        <td class="session-capacity" data-rsvp-target="capacity" data-capacity=<%= session_capacity_text(session)%>><i class="fa-regular fa-user" style="padding-right: 8px;"></i><%= session_capacity_text(session) %></td>
          <td class="session-action">
            <% if session.start_time <= Time.now + 15.minutes %>
              <%= render "books/join_session", book: session.book, session: session %>
            <% elsif session.attendees.exists?(user_id: current_user.id) %>
              <%= render "books/revoke_rsvp", session: session, book: @book %>
            <% elsif session.attendees.count >= session.capacity %>
              <span class="session-full">Full</span>
            <% else %>
              <%= render "books/rsvp", session: session, book: @book %>
            <% end %>
          </td>
        </tr>
      <% end %>
  </tbody>
  <% else %>
    <p>No upcoming sessions.</p>
  <% end %>
</table>
</div>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Show this book", @book %> |
  <%= link_to "Back to books", books_path %>
</div>

app/views/books/index.html.erb
<% @bookshelves.each_with_index do |bookshelf, index| %>
  <% unless bookshelf.name == "Read Books" %>
    <div id="booksCarousel<%= index %>" class="carousel slide mx-auto" data-bs-ride="false">
      <h2 class="carousel-header"><%= bookshelf.name.gsub("_"," ").titleize %></h2>
      <%= render 'carousel', books: bookshelf.books %>
      <button class="carousel-control-prev" type="button" data-bs-target="#booksCarousel<%= index %>" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#booksCarousel<%= index %>" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
      </button>
    </div>
  <% end %>
<% end %>
<br><br>
<br><br>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Back to books", books_path %>
</div>

app/views/books/show.html.erb
<div class="book-show-page-container">
  <div class="book-show-content-container">
    <div class="book-show-book-cover">
      <%= image_tag(@book.image_url, alt: @book.title, class: "img-fluid") %>
    </div>

    <div class="book-show-book-info">
      <h1 class="book-show-book-title"><%= @book.title %></h1>

      <p class="book-show-book-author"><strong>Author:</strong> <%= @book.author %><br>
      Published on <%= @book.date %></p>

      <div class="average-rating d-flex align-items-center">
          <% average = @book.average_rating %>
          <% full_stars = average.floor %>
          <% half_star = average % 0.5 >= 0.25 %>
          <% empty_stars = 5 - full_stars - (half_star ? 1 : 0) %>

          <% full_stars.times do %>
            <i class="fas fa-star"></i>
          <% end %>
          <% if half_star %>
            <i class="fas fa-star-half-alt"></i>
          <% end %>
          <% empty_stars.times do %>
            <i class="far fa-star"></i>
          <% end %>
        </div>

      <div data-controller="book-description" class="book-description">

        <% if @description_longer_than_250 %>
          <p id="description-preview" data-book-description-target="preview"><%= @preview_description %>...<a href="#" class="read-more" data-book-description-target="link" data-action="click->book-description#toggleDescription">More</a></p>
          <p id="full-description" data-book-description-target="full" style="display: none;"><%= @full_description %> <a href="#" class="read-more" data-book-description-target="link" data-action="click->book-description#toggleDescription">Show Less</a></p>
        <% else %>
          <p><%= @full_description %></p>
        <% end %>
        <div class="title-and-buttons"><%= render 'books/book_show_buttons', book: @book %></div>
      </div>
    </div>
    <%= render "books/sessions_panel"  %>
  </div>
</div>

<div class="reviews-section">
  <div class="reviews-section-content">
    <!-- Use d-flex to make this a flex container and align-items-center to align vertically -->
    <div class="reviews-header d-flex align-items-center justify-content-between">
      <div class="d-flex align-items-center"> <!-- This will align the title and stars horizontally -->
        <p class="mb-0">Reviews</p> <!-- mb-0 removes the bottom margin from the paragraph -->
        <span style="margin-left: 10px; margin-top: 3px;"><%= average %>/5 Rating</span>
      </div>
      <%= render 'reviews/addReviewModal' %> <!-- This will be aligned to the right -->
    </div>
    <br>
    <ul class="review-list">
      <% @book.reviews.each do |review| %>
        <li class="review-item">
          <div class="rating-section">
            <div class="rating-stars">
              <% review.rating.times do %>
                <i class="fas fa-star"></i>
              <% end %>
            </div>
          </div>
          <div class="review-description">
            <%= review.description %>
          </div>
          <div class="review-footer">
            <div class="user-email">
              <i class="fa-regular fa-user" style="padding-right: 8px;"></i> <%= review.user.email %>
            </div>
            <div class="actions">
              <% if current_user && current_user.id == review.user_id %>
                <%= link_to "Edit", edit_review_path(review.id), class: "edit-review-link"%>
                |
                <%= link_to "Delete", review_path(review), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
              <% end %>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
    <br>
  </div>
</div>